name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'   # chỉ chạy khi frontend đổi
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Nếu là dự án thuần HTML/CSS/JS -> KHÔNG cần build
      # Nếu là Vite/React -> bật 3 bước Node dưới đây và chỉnh "npm run build"
      # - uses: actions/setup-node@v4
      #   with: { node-version: '20' }
      # - run: cd frontend && npm ci && npm run build
      # - name: Upload artifact (build output)
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: frontend/dist

      # Trường hợp thuần tĩnh: publish thẳng thư mục frontend
      - name: Upload artifact (static)
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
